export const MOCK_PROPERTIES = [
  {
    $id: "mock-property-1",
    title: "Cozy Single Room in Baneshwor",
    description:
      "Perfect for students with all basic amenities. Located in a safe neighborhood with easy access to public transportation. The room comes with a study table, wardrobe, and attached bathroom. WiFi is included in the rent.",
    price: 'Negotiable',
    location: "Baneshwor, Kathmandu",
    address: "Baneshwor-10, Kathmandu",
    roomType: "single",
    amenities: ["WiFi", "Attached Bath", "24/7 Water", "Study Table", "Wardrobe"],
    images: [
      "/single-room.svg?height=300&width=400&text=Room+View",
      "/single-room.svg?height=300&width=400&text=Bathroom",
      "/single-room.png?height=300&width=400&text=Study+Area", 
    ],
    landlordId: "landlord1",
    available: true,
    coordinates: { lat: 27.6915, lng: 85.324 },
    nearbyPlaces: [
      { name: "Tribhuvan University", distance: "2.5 km" },
      { name: "Bus Stop", distance: "200 m" },
      { name: "Local Market", distance: "300 m" },
      { name: "Hospital", distance: "1 km" },
    ],
    rules: [
      "No smoking inside the room",
      "No loud music after 10 PM",
      "Visitors allowed until 9 PM",
      "Monthly rent to be paid by 5th of each month",
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    $id: "mock-property-2",
    title: "Shared Room Near TU",
    description:
      "Affordable shared accommodation perfect for students. Clean and well-maintained with study facilities. Common kitchen available for cooking. Great for making friends with fellow students.",
    price: 5500,
    location: "Kirtipur, Kathmandu",
    address: "Kirtipur-5, Kathmandu",
    roomType: "shared",
    amenities: ["WiFi", "Common Kitchen", "Study Area", "Wardrobe", "Common Bath"],
    images: [
      "/placeholder.svg?height=300&width=400&text=Shared+Room",
      "/placeholder.svg?height=300&width=400&text=Kitchen",
      "/placeholder.svg?height=300&width=400&text=Study+Hall",
    ],
    landlordId: "landlord2",
    available: true,
    coordinates: { lat: 27.6788, lng: 85.2707 },
    nearbyPlaces: [
      { name: "TU Campus", distance: "500 m" },
      { name: "Local Market", distance: "300 m" },
      { name: "Bus Stop", distance: "100 m" },
    ],
    rules: ["Visitors until 9 PM", "Keep common areas clean", "No smoking in common areas"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    $id: "mock-property-3",
    title: "Modern Apartment in New Baneshwor",
    description:
      "Fully furnished modern apartment with all amenities. Perfect for students who want comfort and convenience. Includes kitchen, balcony, and parking space. Located in a prime area with easy access to colleges.",
    price: 'Negotiable',
    location: "New Baneshwor, Kathmandu",
    address: "New Baneshwor-15, Kathmandu",
    roomType: "apartment",
    amenities: ["Furnished", "Balcony", "Parking", "WiFi", "Kitchen", "AC"],
    images: [
      "/placeholder.svg?height=300&width=400&text=Living+Room",
      "/placeholder.svg?height=300&width=400&text=Bedroom",
      "/placeholder.svg?height=300&width=400&text=Kitchen",
      "/placeholder.svg?height=300&width=400&text=Balcony",
    ],
    landlordId: "landlord3",
    available: true,
    coordinates: { lat: 27.6944, lng: 85.3294 },
    nearbyPlaces: [
      { name: "Shopping Mall", distance: "1 km" },
      { name: "Hospital", distance: "800 m" },
      { name: "College", distance: "1.5 km" },
    ],
    rules: ["No pets", "Monthly rent by 5th", "No parties without permission"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    $id: "mock-property-4",
    title: "Budget Room in Koteshwor",
    description:
      "Affordable single room perfect for students on a budget. Located in a quiet residential area with good security. Common bathroom and kitchen facilities available.",
    price: 6500,
    location: "Koteshwor, Kathmandu",
    address: "Koteshwor-14, Kathmandu",
    roomType: "single",
    amenities: ["WiFi", "Common Bath", "24/7 Water", "Study Table"],
    images: [
      "/placeholder.svg?height=300&width=400&text=Room",
      "/placeholder.svg?height=300&width=400&text=Common+Area",
    ],
    landlordId: "landlord4",
    available: true,
    coordinates: { lat: 27.6788, lng: 85.3494 },
    nearbyPlaces: [
      { name: "Bus Stop", distance: "100 m" },
      { name: "Market", distance: "500 m" },
      { name: "College", distance: "2 km" },
    ],
    rules: ["No loud music", "Keep common areas clean", "Guests allowed until 8 PM"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    $id: "mock-property-5",
    title: "Hostel Style Accommodation",
    description:
      "Comfortable hostel accommodation with all facilities for students. Includes meals, laundry, and study hall. Perfect for students who want a complete package.",
    price: 4500,
    location: "Pulchowk, Lalitpur",
    address: "Pulchowk-3, Lalitpur",
    roomType: "hostel",
    amenities: ["WiFi", "Common Kitchen", "Study Hall", "Laundry", "Meals Included"],
    images: [
      "/placeholder.svg?height=300&width=400&text=Hostel+Room",
      "/placeholder.svg?height=300&width=400&text=Study+Hall",
      "/placeholder.svg?height=300&width=400&text=Dining+Area",
    ],
    landlordId: "landlord5",
    available: true,
    coordinates: { lat: 27.6747, lng: 85.3182 },
    nearbyPlaces: [
      { name: "Pulchowk Campus", distance: "800 m" },
      { name: "Bus Stop", distance: "200 m" },
      { name: "Hospital", distance: "1.5 km" },
    ],
    rules: ["No smoking", "No alcohol", "Curfew at 10 PM", "Keep noise levels down", "No outside food allowed"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    $id: "mock-property-6",
    title: "Premium Room with AC",
    description:
      "Luxury room with air conditioning and all modern amenities. Private bathroom, high-speed internet, and premium furnishings. Perfect for students who want comfort and privacy.",
    price: 15000,
    location: "Dillibazar, Kathmandu",
    address: "Dillibazar-33, Kathmandu",
    roomType: "single",
    amenities: ["AC", "Attached Bath", "WiFi", "Furnished", "TV", "Refrigerator"],
    images: [
      "/placeholder.svg?height=300&width=400&text=Premium+Room",
      "/placeholder.svg?height=300&width=400&text=Bathroom",
      "/placeholder.svg?height=300&width=400&text=Balcony+View",
    ],
    landlordId: "landlord6",
    available: true,
    coordinates: { lat: 27.7041, lng: 85.3218 },
    nearbyPlaces: [
      { name: "City Center", distance: "1 km" },
      { name: "Shopping Mall", distance: "500 m" },
      { name: "University", distance: "2 km" },
    ],
    rules: [
      "No smoking inside",
      "No loud parties",
      "No pets",
      "Visitors allowed until 9 PM",
      "Electricity charges extra",
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
